/** Beginner vocabulary for the word typing drill. */
export interface Word {
  word: string;
  meaning: string;
}

export const WORDS: Word[] = [
  // Everyday words
  { word: "사랑", meaning: "love" },
  { word: "친구", meaning: "friend" },
  { word: "가족", meaning: "family" },
  { word: "학교", meaning: "school" },
  { word: "학생", meaning: "student" },
  { word: "선생님", meaning: "teacher" },
  { word: "이름", meaning: "name" },
  { word: "시간", meaning: "time" },
  { word: "오늘", meaning: "today" },
  { word: "내일", meaning: "tomorrow" },
  { word: "어제", meaning: "yesterday" },
  { word: "아침", meaning: "morning" },
  { word: "저녁", meaning: "evening" },
  { word: "집", meaning: "house" },
  { word: "책", meaning: "book" },
  { word: "의자", meaning: "chair" },
  { word: "전화", meaning: "phone" },
  { word: "컴퓨터", meaning: "computer" },
  { word: "영화", meaning: "movie" },
  { word: "음악", meaning: "music" },
  { word: "노래", meaning: "song" },
  { word: "한국", meaning: "Korea" },
  { word: "한국어", meaning: "Korean (language)" },
  { word: "한글", meaning: "Hangul" },
  // Food
  { word: "음식", meaning: "food" },
  { word: "물", meaning: "water" },
  { word: "우유", meaning: "milk" },
  { word: "커피", meaning: "coffee" },
  { word: "사과", meaning: "apple" },
  { word: "딸기", meaning: "strawberry" },
  { word: "빵", meaning: "bread" },
  { word: "쌀", meaning: "uncooked rice" },
  { word: "김치", meaning: "kimchi" },
  { word: "비빔밥", meaning: "bibimbap" },
  { word: "떡볶이", meaning: "tteokbokki" },
  { word: "짜장면", meaning: "jajangmyeon" },
  { word: "과자", meaning: "snack" },
  { word: "닭", meaning: "chicken" },
  // Nature and seasons
  { word: "하늘", meaning: "sky" },
  { word: "바다", meaning: "sea" },
  { word: "나무", meaning: "tree" },
  { word: "꽃", meaning: "flower" },
  { word: "날씨", meaning: "weather" },
  { word: "봄", meaning: "spring" },
  { word: "여름", meaning: "summer" },
  { word: "가을", meaning: "autumn" },
  { word: "겨울", meaning: "winter" },
  { word: "고양이", meaning: "cat" },
  { word: "강아지", meaning: "puppy" },
  { word: "귀", meaning: "ear" },
  // Phrases
  { word: "안녕하세요", meaning: "hello" },
  { word: "감사합니다", meaning: "thank you" },
  { word: "미안해요", meaning: "I'm sorry" },
  { word: "괜찮아요", meaning: "it's okay" },
  { word: "맛있어요", meaning: "it's delicious" },
  { word: "좋아요", meaning: "I like it" },
  { word: "사랑해요", meaning: "I love you" },
  { word: "배고파요", meaning: "I'm hungry" },
  { word: "없어요", meaning: "there isn't any" },
  { word: "왜", meaning: "why" },
  { word: "값", meaning: "price" },
];
